#!/bin/bash -l
#
# Run this file using 'qsub its_clustalo.qsub path/to/input.fasta path/to/matrix.mat path/to/msa.sto'

# All lines starting with "#$" are SGE qsub commands

# Specify a project to run under
#$ -P bi720

# Give this job a name
#$ -N its_clustalo

# Join standard output and error to a single file
#$ -j y

# Name the file where to redirect standard output and error
#$ -o logs/its_clustalo.log

# Send an email when the job finishes
#$ -m eas

# Request a large memory node, this will affect your queue time, but it's better to overestimate
# -l mem_per_core=8G

# Request more cores, this will affect your queue time, make sure your program supports multithreading, or it's a waste
# -pe omp 1

# Now we write the script that the compute node will work on.

source ./common.sh
prerun

# load modules
module load clustalomega/1.2.1

# do some work

datafolder="/projectnb/bi720/MMG/compbio"

infile="$(default $1 ${datafolder}/fungi_its.fasta)"
distout="$(default $2 ${datafolder}/fungi_seq_dist_matrix.mat)"
outfmt="st"
outfile="$(default $3 ${datafolder}/fungi_its_msa.sto)"

# distmat only works with --full, however this slows down the process as it does not use clustering to simplify.

run "clustalo -i $infile --full --distmat-out=$distout -o $outfile --outfmt=$outfmt"

postrun



