#!/bin/bash -l
#
# Run this file using 'qsub its_msa.qsub path/to/input.fasta path/to/output.sto'

# All lines starting with "#$" are SGE qsub commands

# Specify a project to run under
#$ -P bi720

# Give this job a name
#$ -N its_msa

# Join standard output and error to a single file
#$ -j y

# Name the file where to redirect standard output and error
#$ -o logs/its_msa.log

# Send an email when the job finishes
#$ -m eas

# Request a large memory node, this will affect your queue time, but it's better to overestimate
# -l mem_per_core=8G

# Request more cores, this will affect your queue time, make sure your program supports multithreading, or it's a waste
# -pe omp 1

# Now we write the script that the compute node will work on.

source ./common.sh
prerun

# load modules
module load clustalomega/1.2.1

# do some work

datafolder="/projectnb/bi720/MMG/compbio"

infile="$(default $1 ${datafolder}/fungi_its.fasta)"
outfmt="st"
outfile="$(default $2 ${datafolder}/its_msa.sto)"

run "clustalo -i $infile -o $outfile --outfmt=$outfmt"

postrun



