#!/bin/bash -l
#
# Run this file using 'qsub process_fasta.qsub path/to/input.xfasta path/to/seq.fasta path/to/str.fasta path/to/taxonomy.csv'

# All lines starting with "#$" are SGE qsub commands

# Specify a project to run under
#$ -P bi720

# Give this job a name
#$ -N process_xfasta

# Join standard output and error to a single file
#$ -j y

# Name the file where to redirect standard output and error
#$ -o logs/process_xfasta.log

# Send an email when the job finishes
#$ -m eas

# Now we write the script that the compute node will work on.

source ./common.sh
prerun

# load modules
module load python3/3.12.4

# Input file pattern: reads the input file
infile="$(default $1 ${datafolder}/fungi_its.xfasta)"
seqfile="$(default $2 ${datafolder}/fungi_its_seq.fasta)"
strfile="$(default $3 ${datafolder}/fungi_its_str.fasta)"
taxfile="$(default $4 ${datafolder}/taxonomy_db.csv)"

run "python process_xfasta.py -i $infile --seq $seqfile --str $strfile --taxonomy $taxfile"

postrun



